model:
  NAME: BaseCls
  encoder_args:
    NAME: PointMLPEncoder
    in_channels: 4
    embed_dim: 64
    groups: 1
    res_expansion: 1.0
    activation: "relu"
    bias: False
    use_xyz: False
    normalize: "anchor"
    dim_expansion: [ 2, 2, 2, 2 ]
    pre_blocks: [ 2, 2, 2, 2 ]
    pos_blocks: [ 2, 2, 2, 2 ]
    k_neighbors: [ 24, 24, 24, 24 ]
    reducers: [ 2, 2, 2, 2 ]
  cls_args:
    NAME: ClsHead
    num_classes: 15
    mlps: [512, 256]
    norm_args:
      norm: 'bn1d'

mode: finetune_encoder
pretrained_path: ''      # PATH_TO_PRETRAINED_WEIGHTS

lr: 5.0e-4 
optimizer:
 NAME: 'adamw'
 weight_decay: 0.05

sched: cosine
epochs: 300
t_max: 300
warmup_epochs: 10
min_lr: 1.0e-6
grad_norm_clip: 10